export const GET_MOVIES_ATTEMPT = 'GET_MOVIES_ATTEMPT';
export const GET_MOVIES_FAIL = 'GET_MOVIES_FAIL';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';

export const GET_SIMILAR_MOVIES_ATTEMPT = 'GET_SIMILAR_MOVIES_ATTEMPT';
export const GET_SIMILAR_MOVIES_FAIL = 'GET_SIMILAR_MOVIES_FAIL';
export const GET_SIMILAR_MOVIES_SUCCESS = 'GET_SIMILAR_MOVIES_SUCCESS';

export const GET_SELECTED_MOVIE_ATTEMPT = 'GET_SELECTED_MOVIE_ATTEMPT';
export const GET_SELECTED_MOVIE_FAIL = 'GET_SELECTED_MOVIE_FAIL';
export const GET_SELECTED_MOVIE_SUCCESS = 'GET_SELECTED_MOVIE_SUCCESS';

export const ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST';
export const REMOVE_FROM_WATCHLIST = 'REMOVE_FROM_WATCHLIST';

export const SET_ORDER_LIST = 'SET_ORDER_LIST';
export const SET_LIST = 'SET_LIST';

export const SELECT_MOVIE = 'SELECT_MOVIE';

export const RESET_SELECTED_MOVIE = 'RESET_SELECTED_MOVIE';

export const SET_SELECTED_MOVIE_STATUS = 'SET_SELECTED_MOVIE_STATUS';

export const SET_MOVIE_RATING = 'SET_MOVIE_RATING';